# -*- coding: utf-8 -*-

# 地图霍夫圆参数
MAP_DP = 1
MAP_MIN_DIST = 20
MAP_PARAM1 = 250              # Canny 梯度
MAP_PARAM2 = 15               # 圆心累加阈值
MAP_MIN_RADIUS = 5
MAP_MAX_RADIUS = 30

# 小车霍夫圆参数
CAR_DP = 1
CAR_MIN_DIST = 20
CAR_PARAM1 = 250              # Canny 梯度
CAR_PARAM2 = 15               # 圆心累加阈值
CAR_MIN_RADIUS = 5
CAR_MAX_RADIUS = 15

LOSE_TARGET_TH = 30

ADVANCE_TASK_1_TAKE_OFF_NUM = 30
ADVANCE_TASK_1_LEAVE_START_POINT_NUM = 10
ADVANCE_TASK_1_DETECT_CAR_NUM = 5
ADVANCE_TASK_1_BRAKE_DELAY_NUM = 5
ADVANCE_TASK_1_BRAKE_NUM = 10
ADVANCE_TASK_1_STOP_TP_CAR_NUM = 500
ADVANCE_TASK_1_LAND_NUM = 500